version: '3'
services:
    web:
        build:
            context: '.docker'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                UBUNTU_VERSION: '${UBUNTU_VERSION}'
                PHP_VERSION: '${PHP_VERSION}'
                COMPOSER_VERSION: '${COMPOSER_VERSION}'
                NODE_VERSION: '${NODE_VERSION}'
                NPM_VERSION: '${NPM_VERSION}'
                YARN_VERSION: '${YARN_VERSION}'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${HMR_PORT:-8080}:8080'
        environment:
            WWWUSER: '${WWWUSER}'
        volumes:
            - '../.:/var/www/html'
        networks:
            - local
        depends_on:
            - mariadb
            - redis
        container_name: ${APP_NAME}_web

    mariadb:
        image: 'mariadb:${MARIADB_VERSION}'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USER}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'mariadb:/var/lib/mysql'
        networks:
            - local
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
        container_name: ${APP_NAME}_mariadb

    phpmyadmin:
        image: 'phpmyadmin:latest'
        ports:
            - 8081:80
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        links:
            - "mariadb:db"
        depends_on:
            - mariadb
        networks:
            - local
        container_name: ${APP_NAME}_phpmyadmin

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis:/data'
        networks:
            - local
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
        container_name: ${APP_NAME}_redis

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - local
        container_name: ${APP_NAME}_mailhog

networks:
    local:
        driver: bridge
volumes:
    mariadb:
        driver: local
    redis:
        driver: local
